// Code generated by mockery v2.0.3. DO NOT EDIT.

package mocks

import (
	dto "github.com/diarikom/running-app/running-app-api/internal/api/dto"
	mock "github.com/stretchr/testify/mock"
)

// DiscoverContentService is an autogenerated mock type for the DiscoverContentService type
type DiscoverContentService struct {
	mock.Mock
}

// GetContents provides a mock function with given fields: skip, limit
func (_m *DiscoverContentService) GetContents(skip int64, limit int8) (*dto.DiscoverContentResp, error) {
	ret := _m.Called(skip, limit)

	var r0 *dto.DiscoverContentResp
	if rf, ok := ret.Get(0).(func(int64, int8) *dto.DiscoverContentResp); ok {
		r0 = rf(skip, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.DiscoverContentResp)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(int64, int8) error); ok {
		r1 = rf(skip, limit)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
