// Code generated by mockery v2.0.0-alpha.2. DO NOT EDIT.

package mocks

import (
	nfacebook "github.com/diarikom/running-app/running-app-api/internal/pkg/nfacebook"
	mock "github.com/stretchr/testify/mock"
)

// FacebookProviderComponent is an autogenerated mock type for the FacebookProviderComponent type
type FacebookProviderComponent struct {
	mock.Mock
}

// GetUrl provides a mock function with given fields: path
func (_m *FacebookProviderComponent) GetUrl(path string) string {
	ret := _m.Called(path)

	var r0 string
	if rf, ok := ret.Get(0).(func(string) string); ok {
		r0 = rf(path)
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// InspectToken provides a mock function with given fields: token
func (_m *FacebookProviderComponent) InspectToken(token string) (*nfacebook.TokenData, error) {
	ret := _m.Called(token)

	var r0 *nfacebook.TokenData
	if rf, ok := ret.Get(0).(func(string) *nfacebook.TokenData); ok {
		r0 = rf(token)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*nfacebook.TokenData)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(token)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
