// Code generated by mockery v2.0.0-alpha.2. DO NOT EDIT.

package mocks

import (
	io "io"

	mock "github.com/stretchr/testify/mock"
)

// S3Provider is an autogenerated mock type for the S3Provider type
type S3Provider struct {
	mock.Mock
}

// Upload provides a mock function with given fields: file, contentType, dest, scope
func (_m *S3Provider) Upload(file io.Reader, contentType string, dest string, scope int) error {
	ret := _m.Called(file, contentType, dest, scope)

	var r0 error
	if rf, ok := ret.Get(0).(func(io.Reader, string, string, int) error); ok {
		r0 = rf(file, contentType, dest, scope)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
